### ISSUE TITLE
'plays since' not rendering correctly

### ISSUE THREAD

**Issue by chrisvogt** [Granze/lastfm-card#2]
About to submit a PR to fix this - you can see it in effect on the project's [gh-pages demo](http://granze.github.io/lastfm-card/components/lastfm-card/demo.html)

![date-sample](https://cloud.githubusercontent.com/assets/1934719/5604559/1d3d3566-9381-11e4-924b-99b1fdb0fadd.PNG)

**Comment by Granze** [comment]
This is really weird. It works perfectly for me on the demo.
Which browser/version are you using?

**Comment by chrisvogt** [comment]
Really weird! I just now tested it in four browsers on Windows 8.1 - Firefox, Chrome, IE, and Opera. Both Firefox v34.0.5 and IE v11.0.9_x_ present with the issue, but Chrome and Opera show the date fine. 

I just verified the patch I submitted above does fix the issue.

Perhaps the JS engines for those two browsers has issues with using bracket notation? I'm no expert on JavaScript, what is `['#text']`? Is that a syntactic shortcut which might not play well across browsers?

![issue-only-in-ff-ie](https://cloud.githubusercontent.com/assets/1934719/5656308/98ce7e60-9697-11e4-94a0-25bffe2f9646.PNG)

**Comment by Granze** [comment]
Thank you so much for testing this!

I was able to find out what was the problem: Firefox and IE are unable to parse the date string returned by the Lastfm API correctly because of the space between date and time.

2007-03-16 18:48 (this doesn't works)
2007-03-16T18:48 (this works)
2007/03/16 18:48 (this works too)

**Comment by chrisvogt** [comment]
Interesting. By accessing it through dot notation does it automatically
escape the characters? I still don't yet see how  changing the syntax fixed
it.

**Comment by Granze** [comment]
The problem is the string returned by Lastfm is not standard. If you combine date and time, you need to separate them with a "T", not a space.
That's it. :)

http://en.wikipedia.org/wiki/ISO_8601

**Comment by chrisvogt** [comment]
Ah, I see! Thank you.

​
Chris Vogt
www.chrisvogt.me
